import {
  faBars,
  faBath,
  faBed,
  faBell,
  faBoxArchive,
  faCamera,
  faChair,
  faClock,
  faCouch,
  faDoorClosed,
  faDoorOpen,
  faDroplet,
  faFan,
  faFire,
  faImage,
  faKitchenSet,
  faLightbulb,
  faLock,
  faPlug,
  faRobot,
  faSeedling,
  faShirt,
  faSnowflake,
  faTable,
  faTemperatureHalf,
  faToggleOn,
  faTv,
  faVolumeHigh,
  faWarehouse,
  faWind,
  faWindowMaximize,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons'

// Icon per decoration kind, with a fallback per family.
const BY_KIND: Record<string, IconDefinition> = {
  sofa: faCouch,
  armchair: faCouch,
  dining_chair: faChair,
  stool: faChair,
  bench: faChair,
  pouf: faChair,
  bookshelf: faBoxArchive,
  wardrobe: faShirt,
  fridge: faSnowflake,
  oven: faFire,
  hob: faFire,
  dishwasher: faKitchenSet,
  kitchen_sink: faDroplet,
  microwave: faKitchenSet,
  washing_machine: faShirt,
  dryer: faShirt,
  toilet: faBath,
  basin: faDroplet,
  bathtub: faBath,
  shower: faDroplet,
  towel_rail: faShirt,
  rug: faImage,
  plant_large: faSeedling,
  plant_small: faSeedling,
  picture: faImage,
  wall_mirror: faImage,
  wall_clock: faClock,
  vase: faSeedling,
  books: faBoxArchive,
  basket: faBoxArchive,
  curtain: faBars,
  tv: faTv,
  tv_wall: faTv,
  soundbar: faVolumeHigh,
  speaker: faVolumeHigh,
  floor_speaker: faVolumeHigh,
  monitor: faTv,
  game_console: faTv,
  projector: faTv,
  projector_screen: faTv,
  radiator: faFire,
  ac_unit: faSnowflake,
  fan_ceiling: faFan,
  fan_standing: faFan,
  fan_tower: faFan,
  air_purifier: faWind,
  humidifier: faDroplet,
  thermostat: faTemperatureHalf,
  blind: faBars,
  roller_shutter: faBars,
  window: faWindowMaximize,
  door: faDoorOpen,
  sliding_door: faDoorClosed,
  sliding_glass: faDoorClosed,
  garage_door: faWarehouse,
  awning: faBars,
  camera: faCamera,
  doorbell: faBell,
  motion_sensor: faBell,
  contact_sensor: faDoorOpen,
  smoke_detector: faBell,
  alarm_panel: faBell,
  smart_lock: faLock,
  air_quality: faWind,
  vacuum_robot: faRobot,
  smart_plug: faPlug,
  switch_panel: faToggleOn,
}

const BY_FAMILY: Record<string, IconDefinition> = {
  light: faLightbulb,
  seating: faCouch,
  table: faTable,
  storage: faBoxArchive,
  bed: faBed,
  kitchen: faKitchenSet,
  laundry: faShirt,
  bathroom: faBath,
  decor: faImage,
  media: faTv,
  climate: faTemperatureHalf,
  cover: faWindowMaximize,
  security: faBell,
  utility: faPlug,
}

export const decorationIcon = (kindId: string, family: string) => BY_KIND[kindId] ?? BY_FAMILY[family] ?? faBoxArchive

export const FAMILY_LABELS: Record<string, string> = {
  light: 'Lights',
  seating: 'Seating',
  table: 'Tables',
  storage: 'Storage',
  bed: 'Beds',
  kitchen: 'Kitchen',
  laundry: 'Laundry',
  bathroom: 'Bathroom',
  decor: 'Decor',
  media: 'Media',
  climate: 'Climate',
  cover: 'Windows and doors',
  security: 'Security and sensors',
  utility: 'Smart home',
}
